### ISSUE TITLE
Spy command glitch

### ISSUE THREAD

**Issue by Mike-Le-Pauvre** [evan3334/ChatRooms#3]
Hello!

I get this glitch where if I do /cr spy all while i'm not in a room it writes what people say in the room they are in and in the global chat. 

In this screen shot I had spy all and tomypc88 was in channel staff.  when he wrote test 1.2.3.4.5.6 it appeared both in channel staff and in global chat. (Included full list of plugins just in case)
![2015-09-24_00 10 22](https://cloud.githubusercontent.com/assets/14815432/10065258/05025bda-6251-11e5-9d63-cbdb8035c168.png)

In this one we just switched roles, I was in staff channel and he was in global chat with spy all.  I didn't write test twice it somhow duplicated it.
![2015-09-24_00 11 16](https://cloud.githubusercontent.com/assets/14815432/10065259/0502ae96-6251-11e5-85e5-e7ad7175d6e6.png)

This glitch only occurs when the spying player is in the global chat so maybe if the global chat is considered as a room for the plugin and is default for everyone who joins (/cr leave would bring you back to this room too) you would avoid this problem.

I also get these errors in console each time this happens

java.lang.NullPointerException
[23:49:27] [Async Chat Thread - #2/WARN]: 	at com.twippy587.ChatRooms.manager.ChatRoomManager.usersInSameChatRoom(ChatRoomManager.java:257)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at com.twippy587.ChatRooms.listener.PlayerChatListener.onPlayerChat(PlayerChatListener.java:52)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at sun.reflect.GeneratedMethodAccessor189.invoke(Unknown Source)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.chat(PlayerConnection.java:1084)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1022)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at net.minecraft.server.v1_8_R3.PacketPlayInChat$1.run(PacketPlayInChat.java:39)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:49:27] [Async Chat Thread - #2/WARN]: 	at java.lang.Thread.run(Unknown Source)

Thanks!

**Comment by evan3334** [comment]
Thanks for reporting this, this seems like a serious problem.
I'll take a look into this as soon as I can.

**Comment by evan3334** [comment]
Just an update on this issue so you know what's going on:
I apologize, I've been busy with school the past 2 days and haven't been able to look at the code. I'm pretty sure I already know what's causing the problem though, so as soon as I get home tonight I should be able to work on a fix for this.

**Comment by evan3334** [comment]
I've posted resource update 2.3.0 which should hopefully fix your problem. Please let me know if it does not work for you so I can deploy a fix ASAP
Link to the update: https://www.spigotmc.org/resources/chatrooms.8771/update?update=46646

**Comment by Mike-Le-Pauvre** [comment]
Yep it worked thanks!

**Comment by evan3334** [comment]
Issue closed.
